development:
  #:address: smtp.live.com
  :address: smtp.gmail.com
  :port: 587
  :Domain: mail.google.com
  :authentication: plain
  :user_name: priyanko.dey33@gmail.com
  :password: priyanko123456
  :enable_starttls_auto: true        

